default_language_version:
  python: python3
repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [ python ]
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [ python ]
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [ python ]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        name: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: [ "bandit[toml]" ]
        types: [ python ]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [ python ]

  