[tool.bandit]
exclude_dirs = ["tests", "features"]

[tool.black]
max-line-length = 99
target-version = ['py310', 'py311']

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
ignore_missing_imports = true


[tool.poetry]
name = "cakemold"
version = "0.0.1"
description = "Cake Mold is a template to build python projects"
authors = ["Luís Miranda <luistm@gmail.com>"]
license = "The Unlicence"
readme = "README.md"
packages = [{include = "cakemold", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
bandit = {extras = ["toml"], version = "^1.7.4"}
behave = "~1.2.6"
black = "~22.10"
coverage = "~6.5"
flake8 = "~5.0.4"
isort = "~5.10.1"
mypy = "~0.982"
pre-commit = "~2.20.0"
pytest = "~7.2.0"
pytest-xdist = "~3.0.2"
pytest-bdd = "~6.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
