[tool.poetry]
name = "cake-mold"
version = "0.0.1"
description = "Cake Mold is a template to build python projects"
authors = ["Luís Miranda <luistm@gmail.com>"]
license = "The Unlicence"
readme = "README.md"
packages = [{include = "cake_mold"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
